name: local wheel test

on:
  push:

jobs:
  run_test_ubuntu_20_04:
    name: Check that Ubuntu 20.04 package can be installed from local pip
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build local wheel
        run: |
          cat /proc/cpuinfo
          pip3 install wheel
          python3 setup.py sdist bdist_wheel
      - name: Install QSim
        run: |
          pip3 install dist/qsimcirq-0.10.0.dev20210623-cp38-cp38-linux_x86_64.whl
      - name: Run tests
        run: |
          rm -rf qsimcirq/
          pytest qsimcirq_tests/qsimcirq_test.py
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl