on:
  push:
    branches:
      # Only check pushes to master
      - master
    paths:
      # Only check formatting when python files are changed.
      - '**/*.py'
  pull_request:
    # Check PRs for all branches
    paths:
      # Only check formatting when python files are changed.
      - '**/*.py'

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install flynt
        run: cat requirements.txt | grep flynt | xargs pip install
      - name: Install black
        run: cat requirements.txt | grep black | xargs pip install
      - name: Format
        run: check/format-incremental
