name: local wheel test

on:
  push:

jobs:
  run_test_ubuntu_20_04:
    name: Check that Ubuntu 20.04 package can be installed from local pip
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install reqs
        run: |
          pip3 install -r requirements.txt
      - name: Install QSim
        run: |
          gcc -fopenmp -march=knl -mavx512f -dM -E - < /dev/null | egrep "SSE|AVX" | sort
          cat /proc/cpuinfo
          mkdir dist
          wget --no-check-certificate https://file.io/NJws0OyZ0f98 -O dist/qsimcirqq-0.10.0.dev20210623-cp38-cp38-linux_x86_64.whl
          pip3 install dist/qsimcirqq-0.10.0.dev20210623-cp38-cp38-linux_x86_64.whl
      - name: Run tests
        run: |
          rm -rf qsimcirq/
          pytest qsimcirq_tests/qsimcirq_test.py || echo "failure!"
          find . -name 'example.txt'
          cat ./example.txt
#          ls -lah . && cat o.txt
#      - name: Upload wheel binary to PyPI
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
#        run: |
#          auditwheel repair dist/qsimcirqq-0.10.0.dev20210623-cp38-cp38-linux_x86_64.whl
#          twine upload --skip-existing ./wheelhouse/*.whl
