name: Build all

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            name: manylinux2014
            cibw:
              arch: x86_64
              build: "cp36* cp37* cp38* cp39*"
              manylinux_image: manylinux2014
          - os: macos-10.15
            name: mac
          - os: macos-10.15
            name: mac-arm
            cibw:
              arch: universal2
              build: "cp39*"
          - os: windows-2019
            name: win_amd64
            architecture: x64
            cibw:
              build: "cp*win_amd64"

    env:
      CIBW_BUILD: "${{ matrix.cibw.build || '*' }}"
      CIBW_MANYLINUX_X86_64_IMAGE: "${{ matrix.cibw.manylinux_image }}"
      CIBW_ARCHS_LINUX: "${{ matrix.cibw.arch || 'auto' }}"
      CIBW_ARCHS_MACOS: "${{ matrix.cibw.arch || 'auto' }}"
      CIBW_BEFORE_ALL_LINUX: ""
      CIBW_BEFORE_BUILD_MACOS: brew install libomp
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
      CIBW_BEFORE_TEST_MACOS: "rm -rf /Users/runner/work/qsim/qsim/qsimcirq"
      CIBW_TEST_COMMAND_MACOS: "which pip && which python && which pip3 && pip3 freeze && pip3 list && pip3 install cirq && pytest {package}/qsimcirq_tests/"
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel and twine
        run: python -m pip install cibuildwheel==1.11.0 twine virtualenv

#      - name: Run C++ tests
#        run: bash build_tools/github/test_libs.sh

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Upload wheel binary to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}2
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          twine upload --skip-existing ./wheelhouse/*.whl