name: Build all

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [36, 37, 38, 39]
      include:
        - os: ubuntu-latest
          platform_id: manylinux_x86_64
    env:
      CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
      CIBW_BEFORE_ALL_LINUX: yum remove -y cmake && yum install -y openssl-devel wget && wget https://cmake.org/files/v3.20/cmake-3.20.2.tar.gz && tar zxf cmake-3.* && cd cmake-3.* && ./bootstrap && make install

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.11.0

      - name: Install OpenMP
        if: runner.os == 'Macos'
        run: brew install libomp

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl